#!/bin/bash

# $1: inputfile
# $2: outputfile
# $3: output error (if any)

####################
# Fields to Parse
####################
# Fields accepted: created_at, id, user_id, status
#

cat $1 | awk -v outputFile=$2 -v errorFile=$3 -v numFields=4 ' BEGIN {
    FS = "[\t]"
    i = 0;
    stdout = "";
    stderr = "";
}
{
    if (NF == numFields) 
    {
        stdout = stdout "<doc>\n";
        stdout = stdout "\t<field name = \"created_at\" >" $1 "</field>\n";
        stdout = stdout "\t<field name = \"id\" >" $2 "</field>\n";
        stdout = stdout "\t<field name = \"user_id\" >" $3 "</field>\n";
        stdout = stdout "\t<field name = \"status\" >" $4 "</field>\n";
        stdout = stdout "</doc>\n"
    }
    else {
        stderr = stderr $0 "\n";
    }
}
END {
    print stdout > outputFile;
    print stderr > errorFile;
}
'
