#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# $1 : file
# $2 : URL
# $3 : log

# Check parameter number
if [ "$#" -ne 3 ]; then
    echo -e "Wrong number of parameters"
    echo -e "Usage: send file luceneURL error"
    exit 1
fi

file=$1
url=$2
log=$3

# Check file
if [ ! -f $file ]
then
    echo -e "File '$file' cannot be found"
    exit 2
fi

echo -e "Posting file $file to $url"
curl $url --data-binary @$file -H 'Content-type:application/xml' -o $log

#send the commit command to make sure all the changes are flushed and visible
curl $url --data-binary '<commit/>' -H 'Content-type:application/xml' -o $log.1

cat $log.1 >> $log
rm $log.1
